"""DeepSeek protocol - Constants and URL definitions."""
from .constants import (
    DeepSeekHost,
    DeepSeekLoginURL,
    DeepSeekCreateSessionURL,
    DeepSeekCreatePowURL,
    DeepSeekCompletionURL,
    DeepSeekContinueURL,
    DeepSeekUploadFileURL,
    DeepSeekFetchFilesURL,
    DeepSeekFetchSessionURL,
    DeepSeekDeleteSessionURL,
    DeepSeekDeleteAllSessionsURL,
    DeepSeekCompletionTargetPath,
    DeepSeekUploadTargetPath,
    BaseHeaders,
    KeepAliveTimeout,
    StreamIdleTimeout,
    MaxKeepaliveCount,
)

__all__ = [
    "DeepSeekHost",
    "DeepSeekLoginURL",
    "DeepSeekCreateSessionURL",
    "DeepSeekCreatePowURL",
    "DeepSeekCompletionURL",
    "DeepSeekContinueURL",
    "DeepSeekUploadFileURL",
    "DeepSeekFetchFilesURL",
    "DeepSeekFetchSessionURL",
    "DeepSeekDeleteSessionURL",
    "DeepSeekDeleteAllSessionsURL",
    "DeepSeekCompletionTargetPath",
    "DeepSeekUploadTargetPath",
    "BaseHeaders",
    "KeepAliveTimeout",
    "StreamIdleTimeout",
    "MaxKeepaliveCount",
]
